global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['localhost:8080']
#  - job_name: 'spring_actuator'
#    metrics_path: /actuator/prometheus
#    scrape_interval: 5s

